FROM python:3.10

WORKDIR /app
COPY . /app

# Install system libraries
RUN apt-get update && apt-get install -y portaudio19-dev

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose Streamlit port
EXPOSE 8501

# Run app
CMD ["streamlit", "run", "Banking_Iya_Bola_App.py", "--server.port=8501", "--server.address=0.0.0.0"]
